#install the necesarry packages

```{r}
install.packages("dplyr", repos = "http://cran.us.r-project.org")
library("dplyr")
install.packages("ggplot2", repos = "http://cran.us.r-project.org")
library("ggplot2")
install.packages("gplots",repos = "http://cran.us.r-project.org")
library("gplots")
install.packages("ggcorrplot",repos = "http://cran.us.r-project.org")
library("ggcorrplot")
install.packages("simputation", repos = "http://cran.us.r-project.org")
library("simputation")
install.packages("wesanderson", repos = "http://cran.us.r-project.org")
library("wesanderson")
install.packages("recommenderlab", repos = "http://cran.us.r-project.org")
library("recommenderlab")
install.packages("arules", repos = "http://cran.us.r-project.org")
library("arules")
install.packages("Matrix", repos = "http://cran.us.r-project.org")
library("Matrix")
install.packages("reshape2", repos = "http://cran.us.r-project.org")
library("reshape2")
install.packages("forecast", repos = "http://cran.us.r-project.org")
library("forecast") 
library("data.table")
```

#read the csv file into a dataframe. The path to the document depends on where the csv file is saved

```{r}
data <- read.csv("C:/Users/Doina/Desktop/santander/train_santander.csv", stringsAsFactors = FALSE)
```
